---
title: Markusneuschaefer.De
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: 'true'
name: Markus Neuschäfer
job_title: "✅Projekte \U0001F4A1Lernen ❤️Open Culture"
email: m.neuschaefer@gmail.com
description: Willkommen auf meiner Seite, hier notiere ich Gedanken und Links zu Vielem,
  das ich spannend finde. Ich freue mich über Gespräche und Anregungen, erreichbar
  bin ich am besten via <a href='http://twitter.com/mneuschaefer'>Twitter</a> oder
  <a href='mailto:mail@markusneuschaefer.de'>Email</a>.
avatar: "/assets/img/2019/09/mn.jpg"
favicon: "/favicon.ico"
twitter_handler: mneuschaefer
analytics_code: UA-44236559-1
title_image: "/assets/img/2019/09/2019_crop-circles-medium.png"
lang: de_DE
disqus: markusneuschaefer
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
social_networks:
- name: twitter
  url: http://twitter.com/mneuschaefer
- name: linkedin
  url: https://www.linkedin.com/in/markus-neusch%C3%A4fer-5b02076b/
- name: xing
  url: https://www.xing.com/profile/Markus_Neuschaefer
show_categories: 0
show_tags: 0
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 0
future: false
show_drafts: false
url: https://markusneuschaefer.de
baseurl: 
include:
- _pages
permalink: "/:title.html"
category_dir: categories
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
excerpt_separator: "<!-- more -->"
kramdown:
  auto_ids: true
  auto_id_stripping: true
sass:
  sass_dir: assets/partials
  style: compressed
